### ISSUE TITLE
Clarification on config for meltano

### ISSUE THREAD

**Issue by acarter24** [storebrand/target-mssql#17]
I am a little confused about the correct config keys to set in meltano, I am trying to connect to local SQLEXPRESS on Windows 11.

Should I provide only the `sqlalchemy_url`? Do you have an example connection string?

In the tests the separate user/pass/host/dbname are specified.

https://github.com/storebrand/target-mssql/blob/513b6cfdc53b67fa12d4efaaab86b22b021c114d/target_mssql/tests/test_core.py#L21)

Which approach is correct?

EDIT: I think I managed to get this working with:

```
      username: sa
      password: hello
      host: localhost
      port: '1433'
      database: master
      schema: dbo
```

**Comment by hholgersen** [comment]
Thanks for the feedback, it is important to learn what parts of this is confusing. I have attempted to make it so that if you provide a sqlalchemy_url, it will supersede whatever username/password config you have specified. But I don't think I have tested that, so I should probably add a unit-test there.

**Comment by hholgersen** [comment]
It turns out I was wrong, the `sqlalchemy_url` parameter was simply ignored. I have pushed a fix now, so it behaves as I described. above. I have also added some improvements to the documentation, let me know if you have thoughts.

**Comment by hholgersen** [comment]
Closing this for now, let me know if there are other documentations improvements needed.
